//! # Security Layer
//!
//! ETSI TS 103 097 V2.1.1 security services for C-ITS messages.
//!
//! This module provides:
//! - ASN.1 data types generated by `rasn` (COER codec) in [`security_asn`].
//! - ECDSA signing/verification backend in [`ecdsa_backend`].
//! - Certificate handling (ETSI TS 103 097 profiles) in [`certificate`].
//! - Certificate chain storage and validation in [`certificate_library`].
//! - SN-SAP interface types (ETSI TS 102 723-8) in [`sn_sap`].
//! - Message signing service in [`sign_service`].
//! - Message verification service in [`verify_service`].

#[allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused,
    clippy::too_many_arguments
)]
pub mod security_asn;

pub mod certificate;
pub mod certificate_library;
pub mod ecdsa_backend;
pub mod sign_service;
pub mod sn_sap;
pub mod time_service;
pub mod verify_service;
